#
# Copyright 2013-2021 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: 'Compare generated applications'
description: 'Experimental compare generated applications action'
inputs:
  workflow-file-prefix:
    description: 'Workflow file prefix'
    required: false
    default: workflow
  skip-workflow:
    description: 'Application path'
    required: false
    default: >-
      ${{
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.pull_request.title, '[skip ci]') ||
        contains(github.event.pull_request.title, '[ci skip]') ||
        github.event.action == 'closed' ||
        contains(github.event.pull_request.labels.*.name, 'pr: skip-ci')
      }}
outputs:
  matrix:
    description: 'Build Matrix'
    value: ${{ steps.build.outputs.matrix }}
  skip-workflow:
    description: 'Skip workflow'
    value: ${{ inputs.skip-workflow }}
  client:
    description: 'Client files has changed'
    value: ${{ steps.build.outputs.client }}
  common:
    description: 'Common files has changed'
    value: ${{ steps.build.outputs.common }}
  server:
    description: 'Server files has changed'
    value: ${{ steps.build.outputs.server }}
  workspaces:
    description: 'Workspaces files has changed'
    value: ${{ steps.build.outputs.workspaces }}
  any:
    description: 'Any files has changed'
    value: ${{ steps.build.outputs.any }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: 14
    - name: 'Check changes'
      id: build
      run: |
        CLIENT=false
        SERVER=false
        COMMON=false
        WORKSPACES=false
        ANY=false
        if [[ "true" == "${{inputs.skip-workflow}}" ]]; then
          echo "::set-output name=client::${CLIENT}"
          echo "::set-output name=server::${SERVER}"
          echo "::set-output name=common::${COMMON}"
          echo "::set-output name=workspaces::${WORKSPACES}"
          echo "::set-output name=any::${ANY}"
          echo "::set-output name=matrix::{}"
          exit 0
        fi

        echo "::group::Check Angular"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*client/**/angular/**' \
          'generators/*client/**/*-angular*' \
          || ANGULAR=true
        echo "::endgroup::"

        echo "::group::Check React"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*client/**/react/**' \
          'generators/*client/**/*-react*' \
          || REACT=true
        echo "::endgroup::"

        echo "::group::Check Vue"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*client/**/vue/**' \
          'generators/*client/**/*-vue*' \
          || VUE=true
        echo "::endgroup::"

        echo "::group::Check Client Common"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*client/**' \
          ':^*-angular*' \
          ':^**/angular/**' \
          ':^*-react*' \
          ':^**/react/**' \
          ':^*-vue*' \
          ':^**/vue/**' \
          || CLIENT_COMMON=true
        echo "::endgroup::"

        echo "::group::Check Client"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*client/**' \
          || CLIENT=true ANY=true
        echo "::endgroup::"

        echo "::group::Check Server"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/*server/**' \
          'generators/database-changelog' \
          'generators/database-changelog-liquibase' \
          || SERVER=true ANY=true
        echo "::endgroup::"

        echo "::group::Check Common"
        git -c color.ui=always diff --exit-code @~1 -- \
          '.github/actions' \
          '.github/workflows' \
          'generators/*' \
          'generators/app' \
          'generators/bootstrap' \
          'generators/common' \
          'generators/cypress' \
          'generators/entities' \
          'generators/entity' \
          'generators/entity-i18n' \
          'generators/languages' \
          'lib' \
          'test-integration' \
          'utils' \
          || CLIENT=true SERVER=true COMMON=true ANY=true
        echo "::endgroup::"

        echo "::group::Check Workspaces"
        git -c color.ui=always diff --exit-code @~1 -- \
          'generators/workspaces' \
          'generators/docker-compose' \
          || WORKSPACES=true ANY=true
        echo "::endgroup::"

        if [[ "true" == "$ANGULAR" || "true" == "$CLIENT_COMMON" ]]; then
          echo "::group::Workflows Angular"
          test-integration/scripts/99-print-matrix.js generators/client/__workflow/${{ inputs.workflow-file-prefix }}-angular.json
          cat matrix.json
          echo "::endgroup::"
        fi

        if [[ "true" == "$REACT" || "true" == "$CLIENT_COMMON" ]]; then
          echo "::group::Workflows React"
          test-integration/scripts/99-print-matrix.js generators/client/__workflow/${{ inputs.workflow-file-prefix }}-react.json
          cat matrix.json
          echo "::endgroup::"
        fi

        if [[ "true" == "$VUE" || "true" == "$CLIENT_COMMON" ]]; then
          echo "::group::Workflows Vue"
          test-integration/scripts/99-print-matrix.js generators/client/__workflow/${{ inputs.workflow-file-prefix }}-vue.json
          cat matrix.json
          echo "::endgroup::"
        fi

        echo "::set-output name=client::${CLIENT}"
        echo "::set-output name=server::${SERVER}"
        echo "::set-output name=common::${COMMON}"
        echo "::set-output name=workspaces::${WORKSPACES}"
        echo "::set-output name=any::${ANY}"

        MATRIX=$(cat matrix.json)
        rm matrix.json
        MATRIX="${MATRIX//'%'/'%25'}"
        MATRIX="${MATRIX//$'\n'/'%0A'}"
        MATRIX="${MATRIX//$'\r'/'%0D'}"
        echo "::set-output name=matrix::$MATRIX"
      shell: bash
