// Use require to workaround https://github.com/esbuild-kit/esm-loader/issues/41
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

/** @type {typeof import('./application-options.js')} */
export const applicationOptions = require('./application-options');
/** @type {typeof import('./application-types.js')} */
export const applicationTypes = require('./application-types');
/** @type {typeof import('./authentication-types.js')} */
export const authenticationTypes = require('./authentication-types');
/** @type {typeof import('./binary-options.js')} */
export const binaryOptions = require('./binary-options');
/** @type {typeof import('./build-tool-types.js')} */
export const buildToolTypes = require('./build-tool-types');
/** @type {typeof import('./cache-types.js')} */
export const cacheTypes = require('./cache-types');
/** @type {typeof import('./client-framework-types.js')} */
export const clientFrameworkTypes = require('./client-framework-types');
/** @type {typeof import('./database-types.js')} */
export const databaseTypes = require('./database-types');
/** @type {typeof import('./default-application-options.js')} */
export const defaultApplicationOptions = require('./default-application-options');
/** @type {typeof import('./deployment-options.js')} */
export const deploymentOptions = require('./deployment-options');
/** @type {typeof import('./entity-options.js')} */
export const entityOptions = require('./entity-options');
/** @type {typeof import('./entity-table-name-creator.js')} */
export const entityTableNameCreator = require('./entity-table-name-creator');
/** @type {typeof import('./field-types.js')} */
export const fieldTypes = require('./field-types');
/** @type {typeof import('./json-entity.js')} */
export const jsonEntity = require('./json-entity');
/** @type {typeof import('./kubernetes-platform-types.js')} */
export const kubernetesPlatformTypes = require('./kubernetes-platform-types');
/** @type {typeof import('./message-broker-types.js')} */
export const messageBrokerTypes = require('./message-broker-types');
/** @type {typeof import('./monitoring-types.js')} */
export const monitoringTypes = require('./monitoring-types');
/** @type {typeof import('./openapi-options.js')} */
export const openapiOptions = require('./openapi-options');
/** @type {typeof import('./openshift-platform-types.js')} */
export const openshiftPlatformTypes = require('./openshift-platform-types');
/** @type {typeof import('./relationship-options.js')} */
export const relationshipOptions = require('./relationship-options');
/** @type {typeof import('./relationship-types.js')} */
export const relationshipTypes = require('./relationship-types');
/** @type {typeof import('./reserved-keywords.js')} */
export const reservedKeywords = require('./reserved-keywords');
/** @type {typeof import('./search-engine-types.js')} */
export const searchEngineTypes = require('./search-engine-types');
/** @type {typeof import('./service-discovery-types.js')} */
export const serviceDiscoveryTypes = require('./service-discovery-types');
/** @type {typeof import('./test-framework-types.js')} */
export const testFrameworkTypes = require('./test-framework-types');
/** @type {typeof import('./unary-options.js')} */
export const unaryOptions = require('./unary-options');
/** @type {typeof import('./validations.js')} */
export const validations = require('./validations');
/** @type {typeof import('./websocket-types.js')} */
export const websocketTypes = require('./websocket-types');
