/* eslint-disable global-require */
module.exports = {
  applicationOptions: require('./application-options'),
  applicationTypes: require('./application-types'),
  authenticationTypes: require('./authentication-types'),
  binaryOptions: require('./binary-options'),
  buildToolTypes: require('./build-tool-types'),
  cacheTypes: require('./cache-types'),
  clientFrameworkTypes: require('./client-framework-types'),
  databaseTypes: require('./database-types'),
  defaultApplicationOptions: require('./default-application-options'),
  deploymentOptions: require('./deployment-options'),
  entityOptions: require('./entity-options'),
  entityTableNameCreator: require('./entity-table-name-creator'),
  fieldTypes: require('./field-types'),
  jsonEntity: require('./json-entity'),
  kubernetesPlatformTypes: require('./kubernetes-platform-types'),
  messageBrokerTypes: require('./message-broker-types'),
  monitoringTypes: require('./monitoring-types'),
  openapiOptions: require('./openapi-options'),
  openshiftPlatformTypes: require('./openshift-platform-types'),
  relationshipOptions: require('./relationship-options'),
  relationshipTypes: require('./relationship-types'),
  reservedKeywords: require('./reserved-keywords'),
  searchEngineTypes: require('./search-engine-types'),
  serviceDiscoveryTypes: require('./service-discovery-types'),
  testFrameworkTypes: require('./test-framework-types'),
  unaryOptions: require('./unary-options'),
  validations: require('./validations'),
  websocketTypes: require('./websocket-types'),
};
