#! /bin/bash

set -x

if [ ! -d ${OPENSHIFT_DATA_DIR}jdk1.8.0_40 ]
    then
        cd ${OPENSHIFT_DATA_DIR}
        wget -nv http://download.java.net/jdk8u40/archive/b23/binaries/jdk-8u40-ea-bin-b23-linux-x64-27_jan_2015.tar.gz
        tar xvf *.tar.gz
        rm -f *.tar.gz
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}apache-maven-3.3.3 ]
    then
        cd ${OPENSHIFT_DATA_DIR}
        wget -nv http://mirrors.ircam.fr/pub/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
        tar xvf *.tar.gz
        rm -f *.tar.gz
fi
