# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: blog
services:
  zipkin:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 127.0.0.1:9411:9411
