template: |
  ## What’s Changed

  $CHANGES

exclude-contributors:
  - 'dependabot'
categories:
  - title: 💎 Features & Enhancements
    labels:
      - 'area: enhancement :wrench:'
      - 'changes: major :star:'
      - 'changes: minor'
  - title: 🐞 Bug Fixes
    labels:
      - 'area: bug'
      - 'pr: bug-fix'
  - title: 🖥️ Frontend
    labels:
      - 'theme: front'
      - 'theme: vue'
      - 'theme: angular'
      - 'theme: react'
  - title: 🔒 Authentication/Security
    labels:
      - 'theme: OIDC/OAuth2'
      - 'theme: security'
      - 'theme: keycloak"'
  - title: 🐾 JDL/Internals/Blueprints
    labels:
      - 'theme: JDL'
      - 'theme: jhipster-internals'
      - 'theme: blueprint :paw_prints:'
  - title: 🪶 Maven
    labels:
      - 'theme: maven'
  - title: 🐘 Gradle
    labels:
      - 'theme: gradle'
  - title: 📝 Documentation
    label: 'area: documentation:books:'
  - title: 📦 Dependency updates
    label: 'theme: dependencies'
  - title: 💩 Spam/Invalid
    labels:
      - 'spam'
      - 'area: invalid'
