#
# Copyright the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

template: |
  ## What’s Changed

  $CHANGES

exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'app/dependabot'
categories:
  - title: 💎 Features & Enhancements
    labels:
      - 'area: enhancement :wrench:'
      - 'changes: major :star:'
      - 'changes: minor'
  - title: 🐞 Bug Fixes
    labels:
      - 'area: bug'
      - 'pr: bug-fix'
  - title: 🖥️ Frontend
    labels:
      - 'theme: front'
      - 'theme: vue'
      - 'theme: angular'
      - 'theme: react'
  - title: 🔒 Authentication/Security
    labels:
      - 'theme: OIDC/OAuth2'
      - 'theme: security'
      - 'theme: keycloak"'
  - title: 🐾 JDL/Internals/Blueprints
    labels:
      - 'theme: JDL'
      - 'theme: jhipster-internals'
      - 'theme: blueprint :paw_prints:'
  - title: 🪶 Maven
    labels:
      - 'theme: maven'
  - title: 🐘 Gradle
    labels:
      - 'theme: gradle'
  - title: 📝 Documentation
    label: 'area: documentation:books:'
  - title: 📦 Dependency updates
    label: 'theme: dependencies'
  - title: 💩 Spam/Invalid
    labels:
      - 'spam'
      - 'area: invalid'
