version: '2'
services:
    <%= baseName.toLowerCase() %>-cassandra:
        container_name: <%= baseName.toLowerCase() %>-cassandra
        build:
            context: .
            dockerfile: cassandra/Cassandra-Cluster.Dockerfile
        environment:
            - CASSANDRA_CONTACT_POINT=<%=baseName.toLowerCase()%>-cassandra
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    <%=baseName.toLowerCase()%>-cassandra-node:
        image: cassandra:2.2.5
        links:
            - <%= baseName.toLowerCase() %>-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
