version: '2'
services:
    <%= baseName.toLowerCase() %>-cassandra:
        container_name: <%= baseName.toLowerCase() %>-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    <%=baseName.toLowerCase()%>-cassandra-node:
        image: cassandra:2.2.5
        links:
            - <%= baseName.toLowerCase() %>-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    <%=baseName.toLowerCase()%>-cassandra-migration:
        container_name: <%=baseName.toLowerCase()%>-cassandra-migration
        links:
            - <%=baseName.toLowerCase()%>-cassandra
        environment:
            - CASSANDRA_CONTACT_POINT=<%=baseName.toLowerCase()%>-cassandra
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
            - USER=docker-cassandra-migration
            # - DEBUG_LOG=1 ## uncomment to show debug logs in the migration
        build:
            context: .
            dockerfile: cassandra/Cassandra-Migration.Dockerfile
        volumes:
            - ../resources/config/cql:/cql:ro
