version: '2'
services:
    <%= baseName.toLowerCase() %>-sonar:
        container_name: <%= baseName.toLowerCase() %>-sonar
        image: sonarqube:5.5-alpine
        ports:
            - 9000:9000
            - 9092:9092
