#!/bin/bash

echo "JH_APP=$JH_APP"
echo "JH_PROFILE=$JH_PROFILE"
echo "JH_RUN_APP=$JH_RUN_APP"
echo "JH_PROTRACTOR=$JH_PROTRACTOR"

echo "JH_HOME=$JH_HOME"
echo "JH_INTEG=$JH_INTEG"
echo "JH_SAMPLES=$JH_SAMPLES"
echo "JH_SCRIPTS=$JH_SCRIPTS"

echo "SPRING_OUTPUT_ANSI_ENABLED=$SPRING_OUTPUT_ANSI_ENABLED"
echo "SPRING_JPA_SHOW_SQL=$SPRING_JPA_SHOW_SQL"
echo "DISABLE_WEBPACK_LOGS=$DISABLE_WEBPACK_LOGS"
