package com.okta.developer.gateway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAllPropertiesEquals(UserData expected, UserData actual) {
        assertUserDataAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAllUpdatablePropertiesEquals(UserData expected, UserData actual) {
        assertUserDataUpdatableFieldsEquals(expected, actual);
        assertUserDataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataAutoGeneratedPropertiesEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataUpdatableFieldsEquals(UserData expected, UserData actual) {
        assertThat(actual)
            .as("Verify UserData relevant properties")
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDataUpdatableRelationshipsEquals(UserData expected, UserData actual) {
        // empty method
    }
}
