package com.okta.developer.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEntityAllPropertiesEquals(NotificationEntity expected, NotificationEntity actual) {
        assertNotificationEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEntityAllUpdatablePropertiesEquals(NotificationEntity expected, NotificationEntity actual) {
        assertNotificationEntityUpdatableFieldsEquals(expected, actual);
        assertNotificationEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEntityAutoGeneratedPropertiesEquals(NotificationEntity expected, NotificationEntity actual) {
        assertThat(actual)
            .as("Verify NotificationEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEntityUpdatableFieldsEquals(NotificationEntity expected, NotificationEntity actual) {
        assertThat(actual)
            .as("Verify NotificationEntity relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEntityUpdatableRelationshipsEquals(NotificationEntity expected, NotificationEntity actual) {
        // empty method
    }
}
