/**
 * Copyright 2013-2026 the original author or authors from the JHipster project.
 *
 * This file is part of the JHipster project, see https://www.jhipster.tech/
 * for more information.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { existsSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import { createImporterFromContent } from '../jdl/jdl-importer.ts';

import { getGithubSamplesGroup, getGithubSamplesGroups } from './github-group.ts';
import { type GitHubMatrix, type GitHubMatrixGroupItem, convertToGitHubMatrix } from './github-matrix.ts';

/** The `.yo-rc.json` keys worth showing in a sample description. */
const CONFIG_KEYS = [
  'applicationType',
  'clientFramework',
  'clientBundler',
  'microfrontend',
  'authenticationType',
  'databaseType',
  'prodDatabaseType',
  'devDatabaseType',
  'reactive',
  'buildTool',
  'cacheProvider',
  'enableHibernateCache',
  'searchEngine',
  'messageBroker',
  'serviceDiscoveryType',
  'websocket',
  'testFrameworks',
  'enableTranslation',
  'languages',
  'cypressCoverage',
  'cypressAudit',
  'graalvmSupport',
];

/** What every sample description has. */
export type BaseSampleDescription = {
  name: string;
  /** The workflow, or samples group, of the sample. */
  workflow: string;
  jobName: string;
  disabled?: boolean;
  sonar?: boolean;
  /** The command that generates the sample. */
  command: string;
  /** The configuration of the application worth showing. */
  config?: Record<string, unknown>;
  generatorOptions?: Record<string, unknown>;
  args?: string;
  environment?: string;
  war?: boolean;
  matrix: { os: string; node: string; java: string };
};

/** A sample generated by the jdl generator. */
export type JDLSampleDescription = BaseSampleDescription & {
  generator: 'jdl';
  /** The inline JDL the sample is generated from. */
  jdl?: string;
  /** `jdl-samples` value of the workflow sample. */
  jdlSamples?: string;
  /** The jdl files the sample is generated from. */
  jdlSampleFiles: string[];
};

/** A sample generated by the app generator from a `.yo-rc.json` file. */
export type YoRcSampleDescription = BaseSampleDescription & {
  generator: 'app';
  yoRcFile?: string;
  entitiesSample?: string;
  /** `.jhipster/*.json` entity files copied to the project. */
  entityFiles: string[];
  /** `jdl-entity` value of the workflow sample. */
  jdlEntity?: string;
  jdlEntityFiles: string[];
};

/** A sample of a `sample-type` the contract does not define, generated by the generate-sample generator of its blueprint. */
export type CustomSampleDescription = BaseSampleDescription & {
  generator: 'custom';
  sampleType?: string;
  /** The file or folder the sample is generated from. */
  sampleFile: string;
};

export type SampleDescription = JDLSampleDescription | YoRcSampleDescription | CustomSampleDescription;

const pickConfig = (config: Record<string, unknown>): Record<string, unknown> =>
  Object.fromEntries(CONFIG_KEYS.filter(key => config[key] !== undefined).map(key => [key, config[key]]));

/** The configuration of a `.yo-rc.json` file worth showing. */
export const readSampleConfig = (yoRcFile: string | undefined): Record<string, unknown> | undefined => {
  if (!yoRcFile || !existsSync(yoRcFile)) return undefined;
  return pickConfig(JSON.parse(readFileSync(yoRcFile, 'utf8'))['generator-jhipster'] ?? {});
};

/** The configuration the first application of a JDL declares, worth showing. */
export const readSampleJDLConfig = (jdl: string): Record<string, unknown> | undefined => {
  try {
    return pickConfig(createImporterFromContent(jdl).import().exportedApplications[0]?.['generator-jhipster'] ?? {});
  } catch {
    // A template JDL completed by the generator options.
    return undefined;
  }
};

export const sampleMatrixOf = (item: GitHubMatrix | undefined): SampleDescription['matrix'] => ({
  os: item?.os ?? '',
  node: item?.['node-version'] ?? '',
  java: item?.['java-version'] ?? '',
});

export type DescribeGithubSamplesOptions = {
  /** The folder of the samples groups. */
  samplesGroupFolder: string;
  /** The groups to describe, every group of the folder when omitted. */
  groups?: string[];
  /** The folder the described files are relative to. */
  root: string;
  /** The command line of the generator, `jhipster` for generator-jhipster, the cli of a blueprint otherwise. */
  cli?: string;
  /** Describes a sample the contract does not define, like a sample folder given with its arguments. */
  describeSample?: (sample: {
    name: string;
    group: string;
    item: GitHubMatrixGroupItem;
    matrix: GitHubMatrix | undefined;
  }) => SampleDescription | undefined;
};

/**
 * Describe the samples of the samples groups: a sample is generated from an inline `jdl`, or from the `jdl` or `yo-rc`
 * (`sample-type`) file `sample-file` (the sample name by default) of the `sample-folder` (the group by default) of the
 * samples groups folder. A sample of another `sample-type` is described by its file only.
 */
export const describeGithubSamples = async ({
  samplesGroupFolder,
  groups,
  root,
  cli = 'jhipster',
  describeSample,
}: DescribeGithubSamplesOptions): Promise<SampleDescription[]> => {
  const relativeToRoot = (file: string) => relative(root, file);
  const descriptions: SampleDescription[] = [];
  for (const group of groups ?? (await getGithubSamplesGroups(samplesGroupFolder))) {
    const { samples } = await getGithubSamplesGroup(samplesGroupFolder, group);
    // The matrix has an entry for each enabled sample, in order; a sample can customize its job-name.
    const entries = convertToGitHubMatrix(samples).include;
    const enabledSamples = Object.keys(samples).filter(name => !samples[name].disabled);
    for (const [name, item] of Object.entries(samples)) {
      const entry = item.disabled ? undefined : entries[enabledSamples.indexOf(name)];
      const custom = describeSample?.({ name, group, item, matrix: entry });
      if (custom) {
        descriptions.push(custom);
        continue;
      }
      const base: BaseSampleDescription = {
        name,
        workflow: group,
        jobName: entry?.['job-name'] ?? name,
        disabled: item.disabled ? true : undefined,
        command: `${cli} generate-sample '${name}'`,
        generatorOptions: item.generatorOptions,
        matrix: sampleMatrixOf(entry),
      };
      const sampleFile = join(samplesGroupFolder, item['sample-folder'] ?? group, item['sample-file'] ?? name);
      let description: SampleDescription;
      if (item.jdl) {
        description = { ...base, generator: 'jdl', jdl: item.jdl, jdlSampleFiles: [], config: readSampleJDLConfig(item.jdl) };
      } else if (item['sample-type'] === 'jdl') {
        description = {
          ...base,
          generator: 'jdl',
          jdlSampleFiles: [relativeToRoot(`${sampleFile}.jdl`)],
          config: readSampleJDLConfig(readFileSync(`${sampleFile}.jdl`, 'utf8')),
        };
      } else if (item['sample-type'] === 'yo-rc') {
        description = {
          ...base,
          generator: 'app',
          yoRcFile: relativeToRoot(join(sampleFile, '.yo-rc.json')),
          config: readSampleConfig(join(sampleFile, '.yo-rc.json')),
          entityFiles: [],
          jdlEntityFiles: [],
        };
      } else {
        description = { ...base, generator: 'custom', sampleType: item['sample-type'], sampleFile: relativeToRoot(sampleFile) };
      }
      descriptions.push(description);
    }
  }
  return descriptions;
};

const table = (rows: string[][]): string => {
  const widths = rows[0].map((_cell, column) => Math.max(...rows.map(row => row[column].length)));
  return rows
    .map(row =>
      row
        .map((cell, column) => cell.padEnd(widths[column]))
        .join('  ')
        .trimEnd(),
    )
    .join('\n');
};

/** What a sample is generated from: jdl, the folder of its `.yo-rc.json` file, or its `sample-type`. */
const sampleSourceColumn = (sample: SampleDescription): string => {
  if (sample.generator === 'jdl') return 'jdl';
  if (sample.generator === 'app') return sample.yoRcFile?.split('/').slice(-2, -1)[0] ?? '';
  return sample.sampleType ?? '';
};

const sampleJDLColumn = (sample: SampleDescription): string => {
  if (sample.generator === 'app') return sample.jdlEntity ?? '';
  if (sample.generator === 'jdl') return sample.jdlSamples ?? '';
  return '';
};

export const formatSamplesList = (samples: SampleDescription[]): string =>
  table([
    ['workflow', 'sample', 'job', 'app sample', 'entities', 'jdl', 'os', 'node', 'java'],
    ...samples.map(sample => [
      sample.workflow,
      sample.name + (sample.disabled ? ' (disabled)' : ''),
      sample.jobName,
      sampleSourceColumn(sample),
      sample.generator === 'app' ? (sample.entitiesSample ?? '') : '',
      sampleJDLColumn(sample),
      sample.matrix.os,
      sample.matrix.node,
      sample.matrix.java,
    ]),
  ]);

export const formatSample = (sample: SampleDescription): string => {
  const lines = [`${sample.name} (${sample.workflow} workflow, job ${sample.jobName}${sample.disabled ? ', disabled' : ''})`];
  lines.push(`command: ${sample.command}`);
  lines.push(`environment: ${sample.matrix.os}, node ${sample.matrix.node}, java ${sample.matrix.java}`);
  if (sample.environment || sample.war) {
    lines.push(`profile: ${sample.environment ?? ''}${sample.war ? ' (war)' : ''}`.trim());
  }
  if (sample.generatorOptions) lines.push(`generator options: ${JSON.stringify(sample.generatorOptions)}`);
  if (sample.args) lines.push(`args: ${sample.args}`);
  const configurationFile = sample.generator === 'app' ? sample.yoRcFile : undefined;
  if (configurationFile || (sample.generator === 'jdl' && sample.jdl)) {
    lines.push('', `configuration${configurationFile ? ` (${configurationFile})` : ''}:`);
  }
  for (const [key, value] of Object.entries(sample.config ?? {})) {
    lines.push(`  ${key}: ${Array.isArray(value) ? value.join(', ') : String(value)}`);
  }
  if (sample.generator === 'app') {
    if (sample.entityFiles.length > 0) {
      lines.push('', `entities (${sample.entitiesSample}):`, ...sample.entityFiles.map(file => `  ${file}`));
    } else if (sample.entitiesSample) {
      lines.push('', `entities: ${sample.entitiesSample}`);
    }
    if (sample.jdlEntityFiles.length > 0) lines.push('', 'jdl entities:', ...sample.jdlEntityFiles.map(file => `  ${file}`));
  } else if (sample.generator === 'custom') {
    lines.push('', `${sample.sampleType ?? 'custom'} sample: ${sample.sampleFile}`);
  } else {
    if (sample.jdlSampleFiles.length > 0) lines.push('', 'jdl samples:', ...sample.jdlSampleFiles.map(file => `  ${file}`));
    if (sample.jdl) lines.push('', 'jdl:', ...sample.jdl.split('\n').map(line => `  ${line}`));
  }
  return lines.join('\n');
};
