/**
 * Copyright 2013-2026 the original author or authors from the JHipster project.
 *
 * This file is part of the JHipster project, see https://www.jhipster.tech/
 * for more information.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { GitHubMatrixGroup } from '../../../lib/ci/index.ts';

// Each sample is generated by its name only (`generate-sample <name>`): its `.yo-rc.json` folder, its entities and its
// options are given here, like the samples of the json workflows.
export const devServerMatrix = {
  angular: {
    'ng-default-esbuild': {
      'app-sample': 'ng-default',
      entity: 'sqllight',
      generatorOptions: { clientBundler: 'esbuild' },
      os: 'macos-latest',
    },
    'ng-default-module-federation': {
      'app-sample': 'ng-default',
      entity: 'sqllight',
      // `auth`, the option of authenticationType.
      generatorOptions: { auth: 'oauth2', microfrontend: true },
    },
    // `e2e:devserver` runs `ng e2e` for angular without microfrontends only - a microfrontend dev
    // server never reports its url to the builder - so each e2e framework needs a non microfrontend
    // angular job to exercise its own angular schematic.
    'ng-default-playwright': {
      'app-sample': 'ng-default-playwright',
      entity: 'sqllight',
      generatorOptions: { clientBundler: 'esbuild' },
    },
  },
  react: {
    'react-default-devserver': {
      'app-sample': 'react-default',
      entity: 'sqllight',
      os: 'macos-latest',
    },
  },
  vue: {
    'vue-default-devserver': {
      'app-sample': 'vue-default',
      entity: 'sqllight',
    },
  },
} satisfies Record<string, GitHubMatrixGroup>;

/** The samples of the devserver workflow, which selects them by the clients a change touches. */
export default { ...devServerMatrix.angular, ...devServerMatrix.react, ...devServerMatrix.vue } satisfies GitHubMatrixGroup;
