<%#
 Copyright 2013-2017 the original author or authors from the JHipster project.

 This file is part of the JHipster project, see http://www.jhipster.tech/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <%= app.baseName.toLowerCase() %>-postgresql
  namespace: <%= kubernetesNamespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: <%= app.baseName.toLowerCase() %>-postgresql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: postgres
        image: <%= DOCKER_POSTGRESQL %>
        env:
        - name: POSTGRES_USER
          value: <%= app.baseName %>
        - name: POSTGRES_PASSWORD
          value:
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: <%= app.baseName.toLowerCase() %>-postgresql
  namespace: <%= kubernetesNamespace %>
spec:
  selector:
    app: <%= app.baseName.toLowerCase() %>-postgresql
  ports:
  - port: 5432
