name: Generated Applications CI
on: [push, pull_request]
env:
    JHI_RUN_APP: 1
    JHI_PROTRACTOR: 0
    JHI_JDK: 11
    JHI_LIB_REPO: https://github.com/jhipster/jhipster.git
    JHI_LIB_BRANCH: release
    JHI_GEN_REPO: https://github.com/jhipster/generator-jhipster.git
    JHI_GEN_BRANCH: master
    SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true
    JHI_E2E_HEADLESS: true
    JHI_SCRIPTS: ./test-integration/scripts
    NG_CLI_ANALYTICS: 'false'
    JHI_GITHUB_CI: true
jobs:
    applications:
        name: ${{ matrix.app-type }} application test suite
        runs-on: ${{ matrix.os }}
        timeout-minutes: 40
        strategy:
            fail-fast: false
            matrix:
                node_version: [12.x]
                os: [ubuntu-latest]
                app-type: [ngx-session-cassandra-fr, ngx-mongodb-kafka-cucumber, ngx-couchbase]
                include:
                    - app-type: ngx-session-cassandra-fr
                      entity: cassandra
                      profile: dev
                    - app-type: ngx-mongodb-kafka-cucumber
                      entity: mongodb
                      profile: dev
                    - app-type: ngx-couchbase
                      entity: couchbase
                      profile: prod
        env:
            JHI_ENTITY: ${{ matrix.entity }}
            JHI_APP: ${{ matrix.app-type }}
            JHI_PROFILE: ${{ matrix.profile }}
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'
            - name: Config git variables
              run: $JHI_SCRIPTS/04-git-config.sh
            - name: Install Jhipster
              run: $JHI_SCRIPTS/10-install-jhipster.sh
            - name: Generate entities
              run: $JHI_SCRIPTS/11-generate-entities.sh
            - name: Generate project
              run: $JHI_SCRIPTS/12-generate-project.sh
            - name: Replace version in generated project
              run: $JHI_SCRIPTS/13-replace-version-generated-project.sh
            - name: Jhipster Info
              run: $JHI_SCRIPTS/14-jhipster-info.sh
            - name: Start docker containers
              run: $JHI_SCRIPTS/20-docker-compose.sh
            - name: Run backend tests
              run: $JHI_SCRIPTS/21-tests-backend.sh
            - name: Run frontend tests
              run: $JHI_SCRIPTS/22-tests-frontend.sh
            - name: Package application
              run: $JHI_SCRIPTS/23-package.sh
            - name: Run e2e tests
              run: $JHI_SCRIPTS/24-tests-e2e.sh
            - name: Sonar analysis
              run: $JHI_SCRIPTS/25-sonar-analyze.sh
