#
# Copyright the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Generators
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'skip_ci*'
  pull_request:
    types: [closed, opened, synchronize, reopened]
    branches:
      - '*'
permissions:
  contents: read

jobs:
  generate-blueprint:
    permissions:
      contents: none
    uses: ./.github/workflows/generator-generate-blueprint.yml
  database-changelog-liquibase:
    permissions:
      contents: none
    uses: ./.github/workflows/generator-database-changelog-liquibase.yml
  check-generators:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [generate-blueprint, database-changelog-liquibase]
    if: always()
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          if ([ 'skipped' == '${{ needs.generate-blueprint.result }}' ] || [ 'success' == '${{ needs.generate-blueprint.result }}' ]) && \
              ([ 'skipped' == '${{ needs.database-changelog-liquibase.result }}' ] || [ 'success' == '${{ needs.database-changelog-liquibase.result }}' ]); then
            exit 0
          fi
          if [ 'closed' == '${{ github.event.action }}' ]; then
            exit 0
          fi
          exit 1
